Repository knative-portability/large-events, pull requests merged in 2019-07, with the labels that each got.

#2 Users mongodb atlas
  users/Dockerfile
  users/app.py
  users/requirements.txt
  users/test.py
Labels: enhancement

#5 Create coverage reports
  .gitignore
  .travis.yml
  README.md
Labels: enhancement

#6 Basic documentation
  CONTRIBUTING.md
  README.md
Labels: documentation

#7 Fix typo in readme
  README.md
Labels: documentation

#9 Connect posts service to db
  posts/app.py
  posts/requirements.txt
Labels: enhancement

#8 Upsert user in users db
  users/app.py
  users/test.py
Labels: enhancement

#4 Created events skeleton and Event class
  .travis.yml
  events/.dockerignore
  events/Dockerfile
  events/app.py
  events/cloudbuild.yaml
  events/requirements.txt
  events/test.py
  pageserve/test.py
Labels: enhancement

#10 Refactor testing to test runner pattern
  .travis.yml
  events/test_events_class.py
  events/test_events_db.py
  events/test_runner.py
  pageserve/test_runner.py
  pageserve/test_serve.py
  posts/test_posts.py
  posts/test_runner.py
  users/test_authorization.py
  users/test_runner.py
  users/test_user_upsertion.py
Labels: cleanup

#14 Clean up mongo connect pylint style
  events/app.py
  posts/app.py
  users/app.py
Labels: cleanup

#12 Fix mislabeled users tests
  users/test_authorization.py
Labels: cleanup

#15 Move event class out of app.py
  .travis.yml
  events/app.py
  events/eventclass.py
  events/test_events_class.py
  events/test_events_db.py
Labels: cleanup

#11 Users allow change authorization
  users/app.py
  users/test_update_authorization.py
Labels: enhancement

#18 Clean up travis (maybe fix coveralls)
  .travis.yml
Labels: bug, cleanup

#19 Get all events
  events/app.py
  events/test_events_db.py
Labels: enhancement

#16 Post upload helper
  posts/app.py
  posts/requirements.txt
  posts/test_post_uploading.py
  posts/test_posts.py
  users/app.py
Labels: enhancement

#21 Fix small bugs discovered when testing with pageserve.
  events/app.py
Labels: bug, cleanup

#17 Post serve fake data
  posts/app.py
Labels: enhancement

#22 Fix JSON serialization error
  events/app.py
Labels: bug, cleanup

#20 Upload post endpoint
  .gitignore
  posts/app.py
  posts/requirements.txt
  posts/test_post_uploading.py
Labels: enhancement

#24 Posts serve from db
  posts/app.py
  posts/test_post_serving.py
Labels: enhancement

#13 Created some basic UI for pageserve
  pageserve/app.py
  pageserve/templates/events.html
  pageserve/templates/index.html
  pageserve/test_serve.py
Labels: enhancement

#25 (XS) Change DBNotConnectedError to inherit from ConnectionError
  events/app.py
  users/app.py
Labels: cleanup

#27 (M) Test routes improve coverage
  posts/app.py
  posts/test_routes.py
  users/app.py
  users/test_routes.py
Labels: cleanup, enhancement

#26 Call events service from pageserve
  .travis.yml
  events/app.py
  pageserve/app.py
  pageserve/test_serve.py
Labels: enhancement

#28 (M) Sign in with google - front-end
  .gitignore
  .travis.yml
  pageserve/app.py
  pageserve/templates/base.html
  pageserve/templates/events.html
  pageserve/templates/index.html
Labels: enhancement

#31 (L) Gauth sign in users back end
  pageserve/templates/base.html
  users/app.py
  users/requirements.txt
  users/test_authentication.py
  users/test_routes.py
  users/test_update_authorization.py
  users/test_user_upsertion.py
Labels: enhancement

#32 Get event info from form data
  events/app.py
  events/test_routes.py
Labels: enhancement

#33 (M) User authenticate preserve is_organizer in db
  users/app.py
  users/test_user_upsertion.py
Labels: bug, enhancement

#34 Create front-end form entry UI
  pageserve/app.py
  pageserve/templates/events.html
  pageserve/templates/index.html
Labels: enhancement

#35 Remove .pyc files
  pageserve/app.pyc
  pageserve/test.pyc
Labels: cleanup

#38 Tests for events DB error and minor cleanup
  events/app.py
  events/test_routes.py
Labels: cleanup

#42 (XS) Posts generate timestamp on upload
  posts/app.py
  posts/test_post_uploading.py
Labels: enhancement
