Repository knative-portability/large-events, pull requests merged in 2019-08, with the labels that each got.

#43 Display posts
  pageserve/app.py
  pageserve/templates/index.html
  pageserve/test_routes.py
  pageserve/test_serve.py
Labels: enhancement

#44 Reorder events app.py functions
  events/app.py
Labels: cleanup

#45 (XS) Posts respresent timestamp as string
  posts/app.py
  posts/test_post_uploading.py
Labels: enhancement

#37 (XL) Pageserve persist login session
  pageserve/app.py
  pageserve/templates/base.html
  pageserve/test_routes.py
  pageserve/test_serve.py
Labels: enhancement, help wanted

#41 (M) Users add edit authorization route
  users/app.py
  users/test_routes.py
Labels: enhancement

#48 (XS) Better coverage reporting
  .travis.yml
Labels: cleanup

#46 Events creation time timestamp as string
  events/app.py
  events/eventclass.py
  events/test_events_class.py
  events/test_events_db.py
  events/test_routes.py
Labels: enhancement

#50 (M) Standardize Apache 2.0 license use in file headers
  events/app.py
  events/eventclass.py
  events/test_events_class.py
  events/test_events_db.py
  events/test_routes.py
  pageserve/app.py
  pageserve/test_serve.py
  users/app.py
Labels: cleanup, documentation

#55 (S) Fix pageserve login bug
  pageserve/templates/base.html
Labels: bug

#47 (S) Query event by name
  events/app.py
  events/test_routes.py
Labels: enhancement

#49 (S) Get event by ID
  events/app.py
  events/eventclass.py
  events/test_events_class.py
  events/test_routes.py
Labels: enhancement

#52 (L) Delete posts endpoint
  posts/app.py
  posts/test_post_deletion.py
  posts/test_routes.py
Labels: enhancement

#51 (XS) Event picker for adding posts
  pageserve/app.py
  pageserve/templates/index.html
Labels: enhancement

#53 Created navbar and basic style improvements
  pageserve/static/style.css
  pageserve/templates/base.html
  pageserve/templates/events.html
  pageserve/templates/index.html
Labels: enhancement

#59 (XS) Fix event.event_id
  pageserve/templates/index.html
Labels: bug

#58 (XS) Fix ID usage from get_user()
  pageserve/app.py
  pageserve/test_routes.py
Labels: bug, cleanup

#56 (M) Pageserve delete post button
  pageserve/app.py
  pageserve/templates/base.html
  pageserve/templates/index.html
  pageserve/test_routes.py
Labels: enhancement

#57 Page content styling
  pageserve/static/style.css
  pageserve/templates/base.html
  pageserve/templates/events.html
  pageserve/templates/index.html
Labels: enhancement

#61 (S) Make add post/event redirect to homepage
  pageserve/app.py
  pageserve/test_routes.py
Labels: bug, enhancement

#60 (XL) Standardize quotation marks
  events/app.py
  events/eventclass.py
  events/test_events_class.py
  events/test_events_db.py
  events/test_routes.py
  pageserve/app.py
  pageserve/templates/base.html
  pageserve/templates/index.html
  pageserve/test_routes.py
  pageserve/test_serve.py
  posts/app.py
  posts/test_post_deletion.py
  posts/test_post_serving.py
  posts/test_post_uploading.py
  posts/test_routes.py
  users/app.py
  users/test_authentication.py
  users/test_authorization.py
  users/test_routes.py
  users/test_update_authorization.py
  users/test_user_upsertion.py
Labels: cleanup

#63 (S) Pageserve handle downed users service
  pageserve/app.py
  pageserve/templates/base.html
  pageserve/test_serve.py
Labels: bug

#64 (M) Users reorder functions
  users/app.py
  users/test_routes.py
Labels: cleanup

#65 (L) Posts reorder functions
  posts/app.py
  posts/test_routes.py
Labels: cleanup

#66 (S) Fix up pylint warnings in events pageserve
  events/app.py
  pageserve/app.py
Labels: cleanup

#67 Create search bar for events
  pageserve/app.py
  pageserve/static/style.css
  pageserve/templates/base.html
  pageserve/templates/search_results.html
  pageserve/test_routes.py
Labels: enhancement

#62 (S) Add event check for authorization
  pageserve/app.py
  pageserve/test_routes.py
Labels: enhancement

#68 (S) Change edit access to is organizer
  events/app.py
  pageserve/app.py
  pageserve/templates/base.html
  pageserve/test_routes.py
  pageserve/test_serve.py
  users/app.py
  users/test_routes.py
Labels: cleanup

#69 (S) Better ui
  pageserve/static/style.css
  pageserve/templates/index.html
Labels: enhancement

#73 Fix events adding is_organizer KeyError
  pageserve/app.py
  pageserve/test_routes.py
Labels: bug

#72 (M) Created links to events in posts
  pageserve/app.py
  pageserve/templates/index.html
  pageserve/test_routes.py
Labels: cleanup, enhancement

#70 (S) Add post check authentication
  pageserve/app.py
  pageserve/templates/index.html
  pageserve/test_routes.py
Labels: bug, enhancement

#75 (XS) Add is_organizer instructions
  users/README.md
Labels: documentation

#74 (S) Fix no image posting
  pageserve/app.py
Labels: bug, enhancement

#78 (M) Posts filter by event backend
  pageserve/app.py
  pageserve/test_routes.py
Labels: enhancement

#71 (S) Text search for searching events by name
  events/app.py
  events/test_routes.py
Labels: enhancement

#77 (XS) Fix/improve delete buttons
  pageserve/static/style.css
  pageserve/templates/index.html
Labels: bug, enhancement

#79 Added UI for filtering posts by event
  pageserve/app.py
  pageserve/static/style.css
  pageserve/templates/events.html
  pageserve/templates/index.html
Labels: enhancement, help wanted

#80 Add clear filter button
  pageserve/static/style.css
  pageserve/templates/index.html
Labels: enhancement

#81 Cleanup and documentation
  .travis.yml
  events/Dockerfile
  events/app.py
  events/cloudbuild.yaml
  events/eventclass.py
  events/test_events_class.py
  events/test_events_db.py
  events/test_routes.py
  pageserve/app.py
  pageserve/static/style.css
  pageserve/templates/events.html
  pageserve/templates/index.html
  pageserve/test_routes.py
  pageserve/test_serve.py
Labels: cleanup, documentation

#82 Reorder pageserve app.py
  pageserve/app.py
Labels: cleanup
